# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hackdavis' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hackdavis
pod 'Firebase/Analytics'
pod 'FirebaseAuth'
pod 'FirebaseDatabase'
pod 'Firebase/Storage'
pod 'SkyFloatingLabelTextField', '~> 3.0'

  target 'HackdavisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HackdavisUITests' do
    # Pods for testing
  end

end
